### ISSUE TITLE
Invalid characters stack trace

### ISSUE THREAD

**Issue by nikpap** [OsiriX-Foundation/kheops#26]

**Comment by semangard** [comment]
The default ErrorReportValve can display stack traces and/or JSP source code to clients when an error occurs. 

=> To avoid this, custom error handling can be configured within each web application. Alternatively, you can explicitly configure an ErrorReportValve and set its showReport attribute to false (https://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Error_Report_Valve)
