### ISSUE TITLE
Keycloack times out (Controller Boot Thread) WFLYCTL0348: Timeout after [300]

### ISSUE THREAD

**Issue by DennisMuchiri** [OsiriX-Foundation/kheops#40]
(Controller Boot Thread) WFLYCTL0348: Timeout after [300] seconds waiting for service container stability. Operation will roll back. Step that first updated the service container was 'add' at address 

Keycloack times out
<img width="1059" alt="Screenshot 2021-12-09 at 21 51 12" src="https://user-images.githubusercontent.com/11217100/145457743-c4609f0c-d877-41b4-a68f-1b316703767b.png">

**Comment by DennisMuchiri** [comment]
@rliechti please help

**Comment by DennisMuchiri** [comment]
@nikpap Please help

**Comment by nikpap** [comment]
Hello @DennisMuchiri, can you try increasing the resources in your server? It seems like insufficient resources is what causing your issue  check out the first few lines of the console).

**Comment by DennisMuchiri** [comment]
@nikpap okay. Does this affect containers running in docker?

**Comment by DennisMuchiri** [comment]
@nikpap I needed to increase resources in my development machine. Thank you. Closing
