### ISSUE TITLE
study_uid and series_uid generation

### ISSUE THREAD

**Issue by DennisMuchiri** [OsiriX-Foundation/kheops#42]
Hello @spalte osirix team. Please provide documentation on how a study_uid, series_uid are generated by the system. Thank you.

**Comment by DennisMuchiri** [comment]
@nikpap please help

**Comment by nikpap** [comment]
Hello @DennisMuchiri, do you mind going a bit more into detail about your use case?

Kheops doesn't generate `study_uid` or `series_uid`, it parses these from the DICOM files.

Feel free to drop me an email at contact@kheops.online with more information about your issue.

Best,
Nick

**Comment by DennisMuchiri** [comment]
I want to create as custom study. Can  you please explain how the data flows when you import a dicom file to the containers does data flow from UI to dicomweb to Authorization, which end points are involved and how does the proxy route this data.
Thank you.

**Comment by nikpap** [comment]
Hello @DennisMuchiri,

I'm assuming by custom study, you mean you want to modify the `study_uid`, `series_uid` or other DICOM tags.
You can find some example DICOM files at our [demo website](https://demo.kheops.online/).
You can modify these DICOM files yourself (or other ones you have), before importing them into Kheops, by using a tool in the DICOM toolkit such as [dcmodify](https://support.dcmtk.org/docs/dcmodify.html).

When you import a DICOM file, for example, by using drag and drop, a POST request is sent to `/api/studies` with the contents of that file.
These pass through the nginx reverse proxy, the Tomcat authorization server, the DICOMweb proxy, the Authorization proxy and finally the dcm4chee PACS.

You can check out how the Reverse Proxy routes the data in the [locations.conf](https://github.com/OsiriX-Foundation/kheops/blob/main/ReverseProxy/locations.conf).
The containers I am referring to can be found in the [architecture diagram](https://docs.kheops.online/img/architecture.svg) for Kheops.

Let me know if you need any further information or would like to schedule a zoom call.

**Comment by DennisMuchiri** [comment]
@nikpap I think you explained it well. Closing
