### ISSUE TITLE
502:Bad gateway  from API using reverse proxy-letsencrypt 

### ISSUE THREAD

**Issue by DennisMuchiri** [OsiriX-Foundation/kheops#48]
Hi @nikpap @spalte @rliechti . I followed the tutorial about securing my installation https://github.com/OsiriX-Foundation/KheopsDocumentation/blob/master/docs/installation/installation.md .Keycloak works fine but after log in api requests don't go through. A 502 response is returned. What am I missing?

<img width="1343" alt="Screenshot 2022-02-13 at 17 45 03 copy" src="https://user-images.githubusercontent.com/11217100/153759278-d3517024-df82-46e3-881b-c1922cef90bb.png">

**Comment by DennisMuchiri** [comment]
@nikpap please help

**Comment by nikpap** [comment]
Hello @DennisMuchiri , could you provide the changes you made to docker-compose.yml and docker-compose.env ?
Are you using Let's Encrypt or a custom certificate?

**Comment by nikpap** [comment]
Both of these files look correct. Can you send me a copy of your docker-compose logs ?

`docker-compose logs`

**Comment by DennisMuchiri** [comment]
@nikpap here it is

https://drive.google.com/file/d/1PfxQlmJAiX_K100qWZTsUYS_7LCQtt0p/view?usp=sharing

**Comment by DennisMuchiri** [comment]
@nikpap no it's still up and running
<img width="1194" alt="Screenshot 2022-02-14 at 14 00 19" src="https://user-images.githubusercontent.com/11217100/153851838-01e6ac85-ea68-4c93-b69a-485b410ec27e.png">
g

**Comment by DennisMuchiri** [comment]
@nikpap
<img width="1191" alt="Screenshot 2022-02-14 at 14 03 27" src="https://user-images.githubusercontent.com/11217100/153852321-e5ec9163-70be-49b6-b893-d4686e4c535b.png">

**Comment by nikpap** [comment]
I just realized that KHEOPS_AUTHORIZATION_PORT` is set to port `8443` in `docker-compose.env`.
I suspect that might be causing the issue. It should be set to `8080`.

If that doesn't work, I think it might be best to set up a Zoom call to debug this issue.

**Comment by DennisMuchiri** [comment]
@nikpap  okay let me try this. If it doesn't work, we'll have the call

**Comment by DennisMuchiri** [comment]
@nikpap  that was the issue. Thanks a alot. Closing.
